#
# dicom-query-retrieve: dqr-role-definition.properties
# XNAT http://www.xnat.org
# Copyright (c) 2005-2020, Washington University School of Medicine
# All Rights Reserved
#
# Released under the Simplified BSD.
#

##DO NOT USE commas in this file
org.nrg.Role=Dqr
org.nrg.Role.Dqr.key=Dqr
org.nrg.Role.Dqr.name=DQR Access
org.nrg.Role.Dqr.warning=This will allow users to request data to be remapped on import.
org.nrg.Role.Dqr.description=This is a custom user role for users who should be able to pull from and push to PACS. Users given this role will be able to import data from PACS and export data to PACS as long as they are on projects that are authorized to use DQR. If the Allow DQR for All Users plugin setting is set to true then this role will no longer be required.