/*
 * dicom-query-retrieve: build.gradle
 * XNAT http://www.xnat.org
 * Copyright (c) 2005-2020, Washington University School of Medicine
 * All Rights Reserved
 *
 * Released under the Simplified BSD.
 */

buildscript {
    ext {
        vXnat = "1.8.0-SNAPSHOT"
    }
}

plugins {
    id "java"
    id "jacoco"
    id "maven-publish"
    id "idea"
    id "eclipse"
    id "com.dorongold.task-tree" version "1.5"
    id "com.palantir.git-version" version "0.12.3"
    id "io.franzbecker.gradle-lombok" version "4.0.0"
    id "io.spring.dependency-management" version "1.0.9.RELEASE"
    id "org.nrg.xnat.build.xnat-data-builder" version "${vXnat}"
}

group "org.nrg.xnatx.plugins"
version "1.0.0-SNAPSHOT"
description "XNAT DICOM Query/Retrieve Plugin"

repositories {
    mavenLocal()
    maven { url "https://maven.imagej.net/content/groups/public" }
    jcenter()
    mavenCentral()
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    maven { url "https://jitpack.io" }
}

sourceCompatibility = 8
targetCompatibility = 8

compileJava {
    options.fork = false
}

sourceSets {
    main {
        java {
            srcDir "build/xnat-generated/src/main/java"
        }
        resources {
            srcDir "build/xnat-generated/src/main/resources"
        }
    }
}

configurations {
    all {
        exclude group: "edu.ucar", module: "netcdf"
        exclude group: "jakarta-regexp"
        exclude group: "net.sf.saxon", module: "Saxon-B"
        exclude group: "org.apache.geronimo.specs"
        exclude module: "pipelineCNDAXNAT"
        exclude module: "xnat-pipeline"
        exclude group: "jamon"
        exclude group: "org.codehaus.jackson"
        exclude group: "junit"
        exclude group: "org.slf4j", module: "slf4j-log4j12"
        exclude group: "ch.qos.logback"
    }
    implementation.extendsFrom(implementAndInclude)
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.enabled = false
        csv.enabled = false
        html.destination file("${buildDir}/jacocoHtml")
    }
}

test {
    useJUnitPlatform {
        includeEngines "junit-jupiter"
        excludeEngines "junit-vintage"
    }
}

dependencyManagement {
    imports {
        mavenBom "org.nrg:parent:${vXnat}"
    }
    generatedPomCustomization {
        enabled = false
    }
}

def vDcm4che = dependencyManagement.importedProperties["dcm4che.version"] as String
def vCommonsCli = dependencyManagement.importedProperties["commons-cli.version"] as String

dependencies {
    implementation enforcedPlatform("org.nrg:parent:${vXnat}")

    implementation "org.nrg.xnat:web"
    implementation "org.nrg.dicom:dicom-edit4"
    implementation "org.nrg.dicom:dicom-edit6"
    implementation "org.nrg:dicom-xnat-util"
    implementation "org.nrg:dicom-xnat-mx"
    implementation "org.springframework:spring-web"
    implementation "org.springframework:spring-tx"
    implementation "org.springframework:spring-jms"
    implementation "org.springframework:spring-jdbc"
    implementation "org.springframework:spring-context"
    implementation "io.springfox:springfox-swagger2"
    implementation "dcm4che:dcm4che-core"
    implementation "dcm4che:dcm4che-net"
    implementation "org.hibernate:hibernate-core"
    implementation "org.hibernate:hibernate-envers"
    implementation "org.hibernate.javax.persistence:hibernate-jpa-2.1-api"
    implementation "com.fasterxml.jackson.core:jackson-core"
    implementation "com.fasterxml.jackson.core:jackson-annotations"
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "org.apache.commons:commons-lang3"
    implementation "org.aspectj:aspectjweaver"
    implementation "javax.validation:validation-api"
    implementation "org.restlet:org.restlet"
    implementation("turbine:turbine") {
        transitive = false
    }

    implementAndInclude("dcm4che.tool:dcm4che-tool-dcmecho:${vDcm4che}") {
        transitive = false
    }
    implementAndInclude("dcm4che.tool:dcm4che-tool-dcmqr:${vDcm4che}") {
        transitive = false
    }
    implementAndInclude("commons-cli:commons-cli:${vCommonsCli}") {
        transitive = false
    }

    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "org.springframework:spring-test"
    testImplementation "com.github.sbrannen:spring-test-junit5"
    testImplementation "org.mockito:mockito-core"
    testImplementation "org.assertj:assertj-core"
    testImplementation "com.h2database:h2"

    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
}

// Pulls in the Jenkins BUILD_NUMBER environment variable if available.
def buildDate = new Date()
def buildNumber = System.getenv().BUILD_NUMBER?.toInteger() ?: "Manual"
def isDirty, branchName, gitHash, gitHashFull, commitDistance, lastTag, isCleanTag

try {
    def gitDetails = versionDetails()
    isDirty = gitVersion().endsWith ".dirty"
    branchName = gitDetails.branchName ?: "Unknown"
    gitHash = gitDetails.gitHash
    gitHashFull = gitDetails.gitHashFull
    commitDistance = gitDetails.commitDistance
    lastTag = gitDetails.lastTag
    isCleanTag = gitDetails.isCleanTag
} catch (IllegalArgumentException e) {
    logger.info "Got an error trying to read VCS metadata from git. It's possible this project is not under VCS control. Using placeholder values for manifest entries."
    isDirty = true
    branchName = "Unknown"
    gitHash = "None"
    gitHashFull = "None"
    commitDistance = 0
    lastTag = "None"
    isCleanTag = false
}

ext.gitManifest = manifest {
    attributes "Application-Name": project.description,
            "Build-Date": buildDate,
            "Build-Number": buildNumber,
            "Implementation-Version": project.version,
            "Implementation-Sha": gitHash,
            "Implementation-Sha-Full": gitHashFull,
            "Implementation-Commit": commitDistance,
            "Implementation-LastTag": lastTag,
            "Implementation-Branch": branchName,
            "Implementation-CleanTag": isCleanTag,
            "Implementation-Dirty": isDirty
}

logger.info """
Building artifacts with manifest attributes:

 * Build-Date:              ${buildDate}
 * Build-Number:            ${buildNumber}
 * Implementation-Version:  ${version}
 * Implementation-Sha-Full: ${gitHashFull}
 * Implementation-Sha:      ${gitHash}
 * Implementation-Commit:   ${commitDistance}
 * Implementation-LastTag:  ${lastTag}
 * Implementation-Branch:   ${branchName}
 * Implementation-CleanTag: ${isCleanTag}
 * Implementation-Dirty:    ${isDirty}
"""

task sourceJar(type: Jar, dependsOn: classes) {
    classifier "sources"
    manifest {
        from gitManifest
    }
    from sourceSets.main.allSource
}

task javadocJar(type: Jar) {
    classifier "javadoc"
    manifest {
        from gitManifest
    }
    from javadoc.destinationDir
}

jar {
    dependsOn test, sourceJar, javadocJar
    enabled = true
    manifest {
        from gitManifest
    }
}

task xnatPluginJar(type: Jar) {
    dependsOn test, sourceJar, javadocJar
    zip64 true
    archiveClassifier.set "xpl"
    manifest {
        from gitManifest
    }
    // files and folders with "-dev" or "--xx" in their name
    // will not be in the compiled jar
    exclude "**/resources/**/*-dev**"
    exclude "**/resources/**/*--xx**"
    from {
        configurations.implementAndInclude.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifacts {
                artifact sourceJar
                artifact javadocJar
                artifact xnatPluginJar
            }

            pom.withXml {
                def root = asNode()
                root.appendNode("name", project.description)
                root.appendNode("url", "https://bitbucket.org/xnatdev/dicom-query-retrieve")
                root.appendNode("inceptionYear", "2019")

                root.appendNode("scm").with {
                    appendNode("url", "https://bitbucket.org/xnatdev/dicom-query-retrieve")
                    appendNode("connection", "scm:https://bitbucket.org/xnatdev/dicom-query-retrieve")
                    appendNode("developerConnection", "scm:git@bitbucket.org:xnatdev/dicom-query-retrieve.git")
                }

                root.appendNode("licenses").appendNode("license").with {
                    appendNode("name", "Simplified BSD 2-Clause License")
                    appendNode("url", "https://xnat.org/about/license.php")
                    appendNode("distribution", "repo")
                }

                root.appendNode("developers").with {
                    appendNode("developer").with {
                        appendNode("id", "mfmckay")
                        appendNode("name", "Mike McKay")
                        appendNode("email", "mfmckay@wustl.edu")
                    }
                    appendNode("developer").with {
                        appendNode("id", "rherrick")
                        appendNode("name", "Rick Herrick")
                        appendNode("email", "jrherrick@wustl.edu")
                    }
                    appendNode("developer").with {
                        appendNode("id", "hortonw")
                        appendNode("name", "Will Horton")
                        appendNode("email", "hortonw@wustl.edu")
                    }
                    appendNode("developer").with {
                        appendNode("id", "moore.c")
                        appendNode("name", "Charlie Moore")
                        appendNode("email", "moore.c@wustl.edu")
                    }
                }
            }
        }
    }
    repositories {
        maven {
            credentials {
                // These properties must be set in the ~/.gradle/gradle.properties file or passed on the Gradle command
                // line in the form -PrepoUsername=foo -PrepoPassword=bar.
                username propertyWithDefault("repoUsername", "username")
                password propertyWithDefault("repoPassword", "password")
            }
            url "https://nrgxnat.jfrog.io/nrgxnat/libs-${project.version.endsWith("-SNAPSHOT") ? "snapshot" : "release"}-local"
        }
    }
}

def propertyWithDefault(String name, Object value) {
    hasProperty(name) ? property(name) : value
}

