####
#### DQR Project Settings Panels
####

projectSettings:
    kind: tabs
    name: dqrAdminPage
    groups:
        dqrSettings: DICOM Query-Retrieve
    contents:
        ${enableDqrTab}
#        ${irbSettingsTab}

enableDqrTab:
    kind: tab
    group: dqrSettings
    label: Enable DQR
    access:
        allow:
            role: Administrator
    contents:
        ${enableDqrPanel}
        ${adminProjectSettingsJS}

enableDqrPanel:
    kind: panel.form
    id: enable-dqr-panel
    label: Enable DQR for Project
    footer: false
    #load: "~/xapi/dqr/adminProjectSettings/{{XNAT.data.projectId}}"
    #action: "~/xapi/dqr/adminProjectSettings"
    #method: POST
    #contentType: json
    contents:
        projectId:
            kind: input.hidden
            value: "?? XNAT.data.projectId"
        customCss:
            tag: style
            content: |
                label.switchbox > input[disabled] + .switchbox-outer {
                    opacity: 0.3;
                    cursor: not-allowed;
                }
        enableDqr:
            kind: panel.input.switchbox
            name: enabled
            id: enable-project-dqr
            label: Enable DQR?
            description: >
                Enable DQR import/export for this project? <i>(Administrators only)</i>
            values: true|false
            onText: Enabled
            offText: Disabled
            element:
                attr:
                    disabled: disabled
                    readonly: readonly

adminProjectSettingsJS:
    tag: "script|src=~/scripts/dqr/adminProjectSettings.js"

# IRB Settings
irbSettingsTab:
    kind: tab
    label: IRB Management
    group: dqrSettings
    contents:
        ${irbSettings}

irbSettings:
    kind: panel
    label: IRB Management
    footer: false
    contents:
        irbNumberInput:
            kind: panel.element
            label: IRB Number
            contents:
                irbNumber:
                    tag: "input#irb-number|name=irbNumber|type=text|size=30|style=width:236px;margin-right:10px;"
                irbNumberSave:
                    tag: "button#save-irb-number.btn.btn1.btn-sm|type=button"
                    content: Save
        irbFileDownload:
            tag: "div#irb-file-download.hidden"
            contents:
                irbFileLinkElement:
                    kind: panel.element
                    label: IRB File
                    contents:
                        irbFileLink:
                            tag: "a#irb-file-link|href=#!"
                            content: (none)
                        irbFileLinkDesc:
                            tag: "div.description"
                            content: (click to download)
        irbFile:
            kind: panel.input.upload
            name: irbFile
            input:
                name: irbFile
                multiple: false
            label: Upload IRB File
            method: PUT
            action: "~/xapi/dqr/projectSettings/{{XNAT.data.projectId}}/irbFile"
            description: >
                Upload new or replace existing IRB file.
                <div id="irb-file-warning" class="hidden" style="margin-top:10px;">
                    <div class="warning" style="display:inline-block;">
                        <i>Previously uploaded files will be replaced and cannot be recovered.</i>
                    </div>
                </div>
        irbSettingsJS:
            tag: "script|src=~/scripts/dqr/irbSettings.js"

#end