#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
    kind: tabs
    name: dqrAdminPage
    groups:
        dqrTabGroup: DICOM Query-Retrieve
    contents:
        ${dqrPacsTab}
        ${dqrHistoryTab}
        #${dqrAnon}

####
#### DQR Site Settings Panels
####

dqrPacsTab:
    kind: tab
    name: dqrPacsTab
    label: DQR Settings
    group: dqrTabGroup
    active: false
    contents:
        ${dqrPacsPanel}
        ${dqrDicomIdentifierPanel}
        ${dqrOtherPreferencePanel}

dqrHistoryTab:
    kind: tab
    name: dqrHistoryTab
    label: Query History
    group: dqrTabGroup
    active: false
    contents:
        ${dqrHistoryPanel}

dqrPacsPanel:
    kind: panel
    name: dqrPacsPanel
    label: Manage DICOM AE (PACS) Connections
    contents:
        dqrPacsTableContainer:
            tag: "div#pacsDiv"
            content: No DICOM AE connections yet
        dqrPacsScript:
            tag: script|src="~/scripts/dqr/PacsAdministration.js"
        dqrPacsCss:
            tag: link|href="~/style/dqr/dqr.css"|rel="stylesheet"|type="text/css"

dqrDicomIdentifierPanel:
    kind: panel
    name: dqrDicomIdentifierPanel
    label: DICOM Object Identifiers
    contents:
        dqrDicomIdentifierHelptext:
            tag: div.message
            content: >
                The DICOM Query Retrieve Plugin adds new DICOM Object Identifiers to your XNAT configuration. In general, these identifiers affect how DICOM metadata is mapped into XNAT-enabled datatypes. Each DICOM SCP Receiver that you have defined in your core XNAT administrative settings will be assigned to use one of these identifiers. <br><br>
                In order to ensure proper project routing on imports, you must have an SCP Receiver defined that uses a DQR-enabled DICOM Object Identifier from this list. Then, your PACS must be configured to send to that SCP Receiver.
            after: >
                <br>
        dqrDicomIdentifierTableContainer:
            tag: div#dqrDicomIdentifierTableContainer

dqrOtherPreferencePanel:
    kind: panel.form
    name: dqrOtherPreferencePanel
    label: Other Preferences
    method: POST
    url: ~/xapi/dqr
    contentType: json
    contents:
        dqrCallingAe:
            kind: panel.input.text
            name: dqrCallingAe
            label: Calling AE Title
            value: 'XNAT'
            placeholder: Calling AE Title
            description: >
                Enter the calling AE Title that should be used for all DICOM queries this site makes. This name is registered with remote PACS and DICOM AEs, along with your server's IP address and SCP Receiver port.
                Changing the AE Title could affect your ability to communicate with your PACS systems.
        pacsAvailabilityCheckFrequency:
            kind: panel.input.text
            name: pacsAvailabilityCheckFrequency
            label: PACS Threads Check Frequency
            value: '1 minute'
            validation: interval onblur
            description: >
                How often to check how many threads are currently configured for each PACS. If there are more threads
                configured than are currently open, additional threads will be opened (if there are more threads open
                than are currently configured, they will be ended once they complete their current PACS request). Uses
                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
        allowAllUsersToUseDqr:
            kind: panel.input.switchbox
            name: allowAllUsersToUseDqr
            label: Allow DQR for All Users
            onText: Enabled
            offText: Disabled
            description: >
                Should all users always be able to use DQR to access PACS, or should only users that are assigned the 'Dqr' role be able to do so?
        allowAllProjectsToUseDqr:
            kind: panel.input.switchbox
            name: allowAllProjectsToUseDqr
            label: Allow DQR for All Projects
            onText: Enabled
            offText: Disabled
            description: >
                Should users be able to import data to all projects using DQR, or only to projects that have DQR enabled in their project settings?
        notifyAdminOnImport:
            kind: panel.input.switchbox
            name: notifyAdminOnImport
            label: Notify Admin on Import
            onText: Enabled
            offText: Disabled
            description: >
                Should an email be sent to the site admin when data is being imported from a PACS?
        assumeSameSessionIfArrivedWithin:
            kind: panel.input.text
            name: assumeSameSessionIfArrivedWithin
            label: Assume Same Session If Arrived Within
            value: '30 minutes'
            validation: interval onblur
            description: >
                If DICOM files with the same Study Instance UID, but different Study ID, arrive within this time period
                of each other, XNAT will assume that they belong in the same session. In cases where different series
                in the same study have different Study IDs, this should be set to a positive number so that these don't
                get split up into multiple sessions. However, if you're more worried about avoiding remapping issues
                when requesting the same session repeatedly in quick succession, this should be set to 0. Uses
                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.

#### DQR History Tab ####

dqrHistoryPanel:
    kind: panel
    name: dqrHistoryPanel
    label: DICOM AE Import Queue and History
    footer: false
    contents:
        dqrQueueContainer:
            tag: div#dqr-queue-container
        dqrHistoryTableContainer:
            tag: div#dqr-history-container
            content: >
                No history to display yet

# PACS Access
pacsAccessTab:
    kind: tab
    label: PACS Access
    group: dqrTabGroup
    contents:
        ${pacsAccessInfo}
        ${pacsAccessPanel}

pacsAccessInfo:
    tag: div.message|style=margin-bottom:20px
    content: >
        Use the controls below to restrict which PACS systems are displayed when initiating an import.

pacsAccessPanel:
    kind: panel
    label: PACS Access Settings
    contents:
        infoText:
            tag: div
            content: >
                (PACS access controls go here)

dqrAnon:
    kind: tab
    label: Anonymization
    group: dqrTabGroup
    contents:
        ${dqrAnonPanel}

dqrAnonPanel:
    kind: panel.form
    label: PACS Import Anonymization
    method: POST
    url: ~/xapi/dqr/anon
    contentType: json
    contents:
        projectId:
            kind: input.hidden
            name: projectId
        dqrAnonEnabled:
            kind: panel.input.switchbox
            name: dqrAnonEnabled
            label: Enabled
            onText: Anon script enabled
            offText: Anon script disabled
            description: >
                Apply anon script to incoming PACS data?
        dqrAnonApplyAll:
            kind: panel.input.switchbox
            name: dqrAnonApplyAll
            label: Apply script
            onText: Apply to <i>all</i> PACS
            offText: Apply only to <i>specified</i> PACS
            description: >
                Apply anon script to ALL PACS defined on this system.
        dqrAnonPACSItems:
            tag: div#dqr-anon-select-pacs.panel-element.disabled
            contents:
                dqrAnonPACS:
                    kind: panel.select.multi
                    name: dqrAnonPACS
                    label: Select PACS
                    options: "$? */data/pacs $:json | :ResultSet:Result"
                    optionMap:
                        label: aeTitle
                    element:
                        style:
                            minWidth: 300px
                    description: >
                        Select PACS system(s) for which to anonymize incoming data.
        dqrAnonScript:
            kind: panel.textarea
            name: anonScript
            label: Anon Script
            code: text
            description: >
                Anonymization script to apply to incoming PACS data. (Double-click to open in a code editor dialog.)

# end
