####
#### DQR Site Settings Panels
####

dqrPacsTab:
    kind: tab
    name: dqrPacsTab
    label: DICOM QRS Settings
    group: dqrTabGroup
    active: false
    contents:
        ${dqrPacsPanel}
        ${dqrDicomIdentifierPanel}
        ${dqrOtherPreferencePanel}

dqrHistoryTab:
    kind: tab
    name: dqrHistoryTab
    label: Query History
    group: dqrTabGroup
    active: false
    contents:
        ${dqrHistoryPanel}

dqrPacsPanel:
    kind: panel
    name: dqrPacsPanel
    label: Manage DICOM AE (PACS) Connections
    contents:
        dqrPacsTableContainer:
            tag: "div#pacsDiv"
            element:
                html: >
                    No DICOM AE connections yet
        dqrPacsScript:
            tag: script|src="~/scripts/dqr/PacsAdministration.js"
        dqrPacsCss:
            tag: link|href="~/style/dqr/dqr.css"|rel="stylesheet"|type="text/css"

dqrDicomIdentifierPanel:
    kind: panel
    name: dqrDicomIdentifierPanel
    label: DICOM Object Identifiers
    contents:
        dqrDicomIdentifierHelptext:
            tag: div.message
            content: >
                The DICOM Query Retrieve Plugin adds new DICOM Object Identifiers to your XNAT configuration. In general, these identifiers affect how DICOM metadata is mapped into XNAT-enabled datatypes. Each DICOM SCP Receiver that you have defined in your core XNAT administrative settings will be assigned to use one of these identifiers. <br><br>
                In order to ensure proper project routing on imports, you must have an SCP Receiver defined that uses a QRS-enabled DICOM Object Identifier from this list. Then, your PACS must be configured to send to that SCP Receiver.
            after: >
                <br>
        dqrDicomIdentifierTableContainer:
            tag: div#dqrDicomIdentifierTableContainer

dqrOtherPreferencePanel:
    kind: panel.form
    name: dqrOtherPreferencePanel
    label: Other Preferences
    method: POST
    url: /xapi/dqr
    contentType: json
    contents:
        dqrCallingAe:
            kind: panel.input.text
            name: dqrCallingAe
            label: Calling AE Title
            value: 'XNAT'
            placeholder: Calling AE Title
            description: >
                Enter the calling AE Title that should be used for all DICOM queries this site makes. This name is registered with remote PACS and DICOM AEs, along with your server's IP address and SCP Receiver port.
                Changing the AE Title could affect your ability to communicate with your PACS systems.
        pacsAvailabilityCheckFrequency:
            kind: panel.input.text
            name: pacsAvailabilityCheckFrequency
            label: PACS Availability Check Frequency
            value: '1 minute'
            validation: interval onblur
            description: >
                How often to check whether there are any PACS requests in the queue whose PACS are now available.
                If the PACS for one or more of the requests is now in its availability interval, the first request to
                enter the queue whose PACS is now available will be executed. Uses
                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.
        notifyAdminOnImport:
            kind: panel.input.switchbox
            name: notifyAdminOnImport
            label: Notify Admin on Import
            onText: Enabled
            offText: Disabled
            description: >
                Should an email be sent to the site admin when data is being imported from a PACS?
#### DQR History Tab ####

dqrHistoryPanel:
    kind: panel
    name: dqrHistoryPanel
    label: DICOM AE Query History
    footer: false
    contents:
        dqrQueueContainer:
            tag: div#dqr-queue-container
        dqrHistoryTableContainer:
            tag: div#dqr-history-container
            content: >
                No history to display yet

# PACS Access
pacsAccessTab:
    kind: tab
    label: PACS Access
    group: dqrTabGroup
    contents:
        ${pacsAccessInfo}
        ${pacsAccessPanel}

pacsAccessInfo:
    tag: div.message|style=margin-bottom:20px
    content: >
        Use the controls below to restrict which PACS systems are displayed when initiating an import.

pacsAccessPanel:
    kind: panel
    label: PACS Access Settings
    contents:
        infoText:
            tag: div
            content: >
                (PACS access controls go here)

dqrAnon:
    kind: tab
    label: Anonymization
    group: dqrTabGroup
    contents:
        ${dqrAnonPanel}

dqrAnonPanel:
    kind: panel.form
    label: PACS Import Anonymization
    method: POST
    url: ~/xapi/dqr/anon
    contentType: json
    contents:
        projectId:
            kind: input.hidden
            name: projectId
        dqrAnonEnabled:
            kind: panel.input.switchbox
            name: dqrAnonEnabled
            label: Enabled
            onText: Anon script enabled
            offText: Anon script disabled
            description: >
                Apply anon script to incoming PACS data?
        dqrAnonApplyAll:
            kind: panel.input.switchbox
            name: dqrAnonApplyAll
            label: Apply script
            onText: Apply to <i>all</i> PACS
            offText: Apply only to <i>specified</i> PACS
            description: >
                Apply anon script to ALL PACS defined on this system.
        dqrAnonPACSItems:
            tag: div#dqr-anon-select-pacs.panel-element.disabled
            contents:
                dqrAnonPACS:
                    kind: panel.select.multi
                    name: dqrAnonPACS
                    label: Select PACS
                    options: "$? */data/pacs $:json | :ResultSet:Result"
                    optionMap:
                        label: aeTitle
                    element:
                        style:
                            minWidth: 300px
                    description: >
                        Select PACS system(s) for which to anonymize incoming data.
        dqrAnonScript:
            kind: panel.textarea
            name: anonScript
            label: Anon Script
            code: text
            description: >
                Anonymization script to apply to incoming PACS data. (Double-click to open in a code editor dialog.)



#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
    kind: tabs
    name: dqrAdminPage
    groups:
        dqrTabGroup: DICOM QRS
    contents:
        ${dqrPacsTab}
        ${dqrHistoryTab}
        #${dqrAnon}

# end
