####
#### DQR Settings Panels
####

dqrPacsPanel:
    kind: panel
    name: dqrPacsPanel
    label: Manage DICOM AE (PACS) Connections
    contents:
        dqrPacsTableContainer:
            tag: "div#pacsDiv"
            element:
                html: >
                    No DICOM AE connections yet
        dqrPacsScript:
            tag: script|src="~/scripts/dqr/PacsAdministration.js"
#            tag: script|src="/scripts/dqr/PacsAdministration.js"
        dqrPacsCss:
            tag: link|href="~/style/dqr/dqr.css"|rel="stylesheet"|type="text/css"
dqrDicomIdentifierPanel:
    kind: panel
    name: dqrDicomIdentifierPanel
    label: DICOM Object Identifiers
    contents:
        dqrDicomIdentifierHelptext:
            tag: div.message
            content: >
                The DICOM Query Retrieve Plugin adds new DICOM Object Identifiers to your XNAT configuration. In general, these identifiers affect how DICOM metadata is mapped into XNAT-enabled datatypes. Each DICOM SCP Receiver that you have defined in your core XNAT administrative settings will be assigned to use one of these identifiers. <br><br>
                In order to enable custom DICOM remapping using the QRS plugin, you must have an SCP Receiver defined that uses a QRS-enabled DICOM Object Identifier from this list. Then, your PACS must be configured to send to that SCP Receiver.
            after: >
                <br>
        dqrDicomIdentifierTableContainer:
            tag: div#dqrDicomIdentifierTableContainer
dqrPushPreferencePanel:
    kind: panel.form
    name: dqrPushPreferencePanel
    label: Image Push Preferences
    method: POST
    url: /xapi/siteConfig
    contentType: json
    contents:
        dqrPushInfo:
            tag: div.message
            content: >
                This setting toggles a site-wide preference for whether an image-push operation should be allowed to include scans that were originally imported with an image session. Enabling this could lead to overwriting data on your DICOM AE destination.
            after: >
                <br>
        dqrPushPreference:
            kind: panel.input.switchbox
            name: dqrPushPreference
            label: Default Scan Send Behavior
            onText: Allow all scans to be sent to DICOM AE
            offText: Allow only new / edited scans to be sent to DICOM AE
            value: "true"
dqrOtherPreferencePanel:
    kind: panel.form
    name: dqrOtherPreferencePanel
    label: Other Preferences
    method: POST
    url: /xapi/dqr
    contentType: json
    contents:
        dqrCallingAe:
            kind: panel.input.text
            name: dqrCallingAe
            label: Calling AE Title
            value: 'XNAT'
            placeholder: Calling AE Title
            description: >
                Enter the calling AE Title that should be used for all DICOM queries this site makes. This name is registered with remote PACS and DICOM AEs, along with your server's IP address and SCP Receiver port.
                Changing the AE Title could affect your ability to communicate with your PACS systems.
        pacsAvailabilityCheckFrequency:
            kind: panel.input.text
            name: pacsAvailabilityCheckFrequency
            label: PACS Availability Check Frequency
            value: '5 minutes'
            validation: interval onblur
            description: >
                How often to check whether there are any PACS requests in the queue whose PACS are now available.
                If the PACS for one or more of the requests is now in its availability interval, the first request to
                enter the queue whose PACS is now available will be executed. Uses
                <a target="_blank" href="http://www.postgresql.org/docs/9.0/static/functions-datetime.html">PostgreSQL interval notation</a>.

#### DQR History Tab ####

dqrHistoryPanel:
    kind: panel
    name: dqrHistoryPanel
    label: DICOM AE Query History
    footer: false
    contents:
        dqrQueueContainer:
            tag: div#dqr-queue-container
        dqrHistoryTableContainer:
            tag: div#dqr-history-container
            contents: No history to display yet


#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
    kind: tabs
    name: dqrAdminPage
    meta:
        tabGroups:
            dqrTabGroup: DICOM QRS
    contains: tabs
    tabs:
        dqrPacsTab:
            kind: tab
            name: dqrPacsTab
            label: DICOM QRS Settings
            group: dqrTabGroup
            active: false
            contents:
              ${dqrPacsPanel}
              ${dqrDicomIdentifierPanel}
              ${dqrPushPreferencePanel}
              ${dqrOtherPreferencePanel}
        dqrHistoryTab:
            kind: tab
            name: dqrHistoryTab
            label: Query History
            group: dqrTabGroup
            active: false
            contents:
              ${dqrHistoryPanel}