####
#### TIP Settings Panels
####

tipPacsPanel:
    kind: panel
    name: tipPacsPanel
    label: Manage DICOM AE (PACS) Connections
    contents:
        tipPacsTableContainer:
            tag: "div#pacsDiv"
            contents: No DICOM AE connections yet
        tipPacsScript:
            tag: script|src="~/scripts/tip/PacsAdministration.js"


#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
    kind: tabs
    name: tipSearchAdminPage
    label: TIP Site Settings
    meta:
        tabGroups:
            tipImageSearchTabGroup: TIP Image Search
    contains: tabs
    tabs:
        tipPacsTab:
            kind: tab
            name: tipPacsTab
            label: Administer PACS
            group: tipImageSearchTabGroup
            active: false
            contents:
              ${tipPacsPanel}